# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# How to install:
# pip install pre-commit
# pre-commit install
# pre-commit run --all-files
# pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Common errors
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

      # Git Errors
      - id: check-added-large-files

      # Python Errors
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
