site_name: { { cookiecutter.package_name } }
repo_url: https://github.com/imanousar/src
site_url: https://imanousar.github.io/src/
site_description: description
site_author: Giannis Manousaridis
use_directory_urls: false

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

nav:
  - Home: index.md
